### ISSUE TITLE
S3 Storage

### ISSUE THREAD

**Issue by Rogerio** [unmantained-activeadmin-plugins/activeadmin-wysihtml5#10]
How can i set s3 storage for this gem?

Thanks

**Comment by stefanoverna** [comment]
Not an issue, take a look here: http://markevans.github.io/dragonfly/file.DataStorage.html#S3_datastore

**Comment by asecondwill** [comment]
is this currently possible?  

dragonfly-s3_data_store (~> 1.0.0) ruby depends on
      dragonfly (~> 1.0) ruby

but actiaveadmin dragonfly 
s.add_dependency "dragonfly", "0.9.15"

**Comment by nebirhos** [comment]
See issue #4.
EDIT: Sorry I meant issue [#4](https://github.com/stefanoverna/activeadmin-dragonfly/issues/4#issuecomment-33005276) on activeadmin-dragonfly :)

TL;DR: remove dragonfly-s3_data_store

**Comment by blackblood** [comment]
I'm using paperclip for handling images and storing them in an aws s3 bucket. How should I configure activeadmin-wysihtml5 to work with paperclip and aws?
