### ISSUE TITLE
I can't upload image with editor wysihtml5

### ISSUE THREAD

**Issue by davidbuenonnoleto** [unmantained-activeadmin-plugins/activeadmin-wysihtml5#13]
I can't upload image with editor, show me 500 internal server error
![error](https://f.cloud.github.com/assets/2189246/951945/932ec8c6-03b7-11e3-84eb-e1e8a942e19b.png)

**Comment by stefanoverna** [comment]
hi @davidbuenonnoleto, you need to be more specific with the exception you're having, otherwise it'll be impossible to guess the reason :) closing for now, feel free to reopen when you have further infos

**Comment by ilsonlasmar** [comment]
hi @davidbuenonnoleto, your problem is mod_security (an extension for apache). this's marking this file as a threat, and refused to serve it up. I suggest disabling mod_security!
Hope this helps!
