### ISSUE TITLE
Sass error

### ISSUE THREAD

**Issue by maxschulze** [unmantained-activeadmin-plugins/activeadmin-wysihtml5#31]
Undefined mixin 'box-shadow'.
  (in /Users/maxschulze/.rvm/gems/ruby-2.1.0/bundler/gems/activeadmin-wysihtml5-c499bc7ee00b/app/assets/stylesheets/activeadmin-wysihtml5/base.css.sass:22)

**Comment by roymckenzie** [comment]
Have this same issue.

**Comment by stefanoverna** [comment]
Merged PR
